worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # Configuração de log
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;

    # Rate limiting básico (opcional, para evitar flood)
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

    upstream nest_api {
        # host.docker.internal resolve para o localhost da sua máquina hospedeira
        # permitindo que o Nginx no Docker acesse a API rodando no 'npm run start:dev'
        server host.docker.internal:3000;
    }

    server {
        listen 80;
        server_name localhost;

        # Headers de Segurança
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Content-Type-Options "nosniff";

        location / {
            # Aplica o rate limit (permite picos de até 20 requisições)
            limit_req zone=api_limit burst=20 nodelay;

            proxy_pass http://nest_api;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            
            # Repassa os IPs reais
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
